// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608160833_AddGameSoftDeleteAndSafeQueries")]
    partial class AddGameSoftDeleteAndSafeQueries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.Entities.BoardCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("CellType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ColIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("State");

                    b.HasIndex("BoardId", "RowIndex", "ColIndex")
                        .IsUnique();

                    b.ToTable("board_cells", null, t =>
                        {
                            t.HasCheckConstraint("CK_board_cells_state_allowed", "\"State\" IN ('open','closed')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.BoardCellMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("CellId", "SortOrder")
                        .IsUnique();

                    b.ToTable("board_cell_media", (string)null);
                });

            modelBuilder.Entity("backend.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("MaxPlayersPerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3);

                    b.Property<short>("MinPlayersPerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsDeleted", "Status", "CreatedAtUtc");

                    b.HasIndex(new[] { "Status" }, "UX_games_single_active")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active' AND \"IsDeleted\" = FALSE");

                    b.HasIndex(new[] { "Status" }, "UX_games_single_draft")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'draft' AND \"IsDeleted\" = FALSE");

                    b.HasIndex(new[] { "Status" }, "UX_games_single_ready")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'ready' AND \"IsDeleted\" = FALSE");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("CK_games_finishedat_semantics", "((\"Status\" IN ('draft','ready','active')) AND \"FinishedAtUtc\" IS NULL) OR ((\"Status\" = 'finished') AND \"FinishedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_games_lifecycle_timestamps", "((\"Status\" = 'draft') AND \"ReadyAtUtc\" IS NULL AND \"StartedAtUtc\" IS NULL AND \"FinishedAtUtc\" IS NULL) OR ((\"Status\" = 'ready') AND \"ReadyAtUtc\" IS NOT NULL AND \"StartedAtUtc\" IS NULL AND \"FinishedAtUtc\" IS NULL) OR ((\"Status\" = 'active') AND \"ReadyAtUtc\" IS NOT NULL AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NULL) OR ((\"Status\" = 'finished') AND \"ReadyAtUtc\" IS NOT NULL AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_games_soft_delete_semantics", "(\"IsDeleted\" = FALSE AND \"DeletedAtUtc\" IS NULL) OR (\"IsDeleted\" = TRUE AND \"DeletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_games_status_allowed", "\"Status\" IN ('draft','ready','active','finished')");

                            t.HasCheckConstraint("CK_games_team_size_limits", "\"MinPlayersPerTeam\" > 0 AND \"MaxPlayersPerTeam\" >= \"MinPlayersPerTeam\"");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameActiveModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ActivatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifierCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ModifierCode");

                    b.HasIndex("ActivatedByUserId", "ActivatedAtUtc");

                    b.HasIndex("GameId", "ActivatedAtUtc");

                    b.HasIndex("GameId", "ModifierCode");

                    b.ToTable("game_active_modifiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_active_modifiers_code_not_blank", "length(trim(\"ModifierCode\")) > 0");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("ColLabels")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Cols")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("RowLabels")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("game_boards", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_boards_dimensions_positive", "\"Rows\" > 0 AND \"Cols\" > 0");

                            t.HasCheckConstraint("CK_game_boards_labels_match_dimensions", "jsonb_array_length(\"RowLabels\") = \"Rows\" AND jsonb_array_length(\"ColLabels\") = \"Cols\"");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameModifierSelection", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifierCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId", "ModifierCode");

                    b.HasIndex("GameId");

                    b.HasIndex("ModifierCode");

                    b.ToTable("game_modifier_selections", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_modifier_selections_code_not_blank", "length(trim(\"ModifierCode\")) > 0");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameParticipationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitedByKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("GameId", "InvitedUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_game_participation_invitations_one_pending_per_user")
                        .HasFilter("\"Status\" = 'pending'");

                    b.HasIndex("GameId", "SlotId");

                    b.HasIndex("GameId", "Status");

                    b.HasIndex("GameId", "TeamId");

                    b.HasIndex("InvitedUserId", "Status");

                    b.ToTable("game_participation_invitations", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_participation_invitations_invited_by_kind", "\"InvitedByKind\" IN ('admin','member')");

                            t.HasCheckConstraint("CK_game_participation_invitations_status", "\"Status\" IN ('pending','accepted','declined','cancelled','expired')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameParticipationSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReservedLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Availability");

                    b.HasIndex("GameId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("game_participation_slots", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_participation_slots_availability", "\"Availability\" IN ('public','reserved')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameQuestionRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnsweredByDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AnsweredByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnsweredForUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AskOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AskedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AskedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AwardedPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubmittedAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AnsweredByUserId", "AnsweredAtUtc");

                    b.HasIndex("AnsweredForUserId", "AnsweredAtUtc");

                    b.HasIndex("AskedByUserId", "AskedAtUtc");

                    b.HasIndex("GameId", "AskOrder")
                        .IsUnique();

                    b.HasIndex("GameId", "AskedAtUtc");

                    b.HasIndex("GameId", "QuestionId")
                        .IsUnique();

                    b.HasIndex("GameId", "Status");

                    b.ToTable("game_question_rounds", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_question_rounds_ask_order_positive", "\"AskOrder\" > 0");

                            t.HasCheckConstraint("CK_game_question_rounds_awarded_points_non_negative_or_null", "\"AwardedPoints\" IS NULL OR \"AwardedPoints\" >= 0");

                            t.HasCheckConstraint("CK_game_question_rounds_status_allowed", "\"Status\" IN ('asked','answered_correct','answered_wrong','timeout','skipped')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DisbandedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RecruitmentOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("GameId", "SlotId");

                    b.HasIndex("GameId", "Status");

                    b.HasIndex(new[] { "SlotId" }, "UX_game_teams_active_slot")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('forming','confirmed')");

                    b.ToTable("game_teams", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_teams_status_allowed", "\"Status\" IN ('forming','confirmed','rejected','disbanded')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.GameTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "TeamId");

                    b.HasIndex("TeamId", "UserId");

                    b.HasIndex(new[] { "GameId", "UserId" }, "UX_game_team_members_active_game_user")
                        .IsUnique()
                        .HasFilter("\"LeftAtUtc\" IS NULL");

                    b.HasIndex(new[] { "TeamId", "UserId" }, "UX_game_team_members_active_team_user")
                        .IsUnique()
                        .HasFilter("\"LeftAtUtc\" IS NULL");

                    b.ToTable("game_team_members", (string)null);
                });

            modelBuilder.Entity("backend.Data.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Bucket", "ObjectKey")
                        .IsUnique();

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_media_assets_scope_allowed", "\"Scope\" IN ('private')");

                            t.HasCheckConstraint("CK_media_assets_status_allowed", "\"Status\" IN ('pending','active')");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.ModifierConflict", b =>
                {
                    b.Property<string>("ModifierCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConflictsWithModifierCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ModifierCode", "ConflictsWithModifierCode");

                    b.HasIndex("ConflictsWithModifierCode");

                    b.ToTable("modifier_conflicts", null, t =>
                        {
                            t.HasCheckConstraint("CK_modifier_conflicts_distinct_codes", "\"ModifierCode\" <> \"ConflictsWithModifierCode\"");
                        });

                    b.HasData(
                        new
                        {
                            ModifierCode = "prokaznik",
                            ConflictsWithModifierCode = "mentorbait"
                        },
                        new
                        {
                            ModifierCode = "mentorbait",
                            ConflictsWithModifierCode = "prokaznik"
                        },
                        new
                        {
                            ModifierCode = "prokaznik",
                            ConflictsWithModifierCode = "krysa"
                        },
                        new
                        {
                            ModifierCode = "krysa",
                            ConflictsWithModifierCode = "prokaznik"
                        },
                        new
                        {
                            ModifierCode = "prokaznik",
                            ConflictsWithModifierCode = "shot"
                        },
                        new
                        {
                            ModifierCode = "shot",
                            ConflictsWithModifierCode = "prokaznik"
                        },
                        new
                        {
                            ModifierCode = "mentorbait",
                            ConflictsWithModifierCode = "krysa"
                        },
                        new
                        {
                            ModifierCode = "krysa",
                            ConflictsWithModifierCode = "mentorbait"
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.ModifierDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActivationCommand")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ActivationCost")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultLimitPerGame")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScoringType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("modifier_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_modifier_definitions_cost_non_negative", "\"ActivationCost\" >= 0");

                            t.HasCheckConstraint("CK_modifier_definitions_kind_allowed", "\"Kind\" IN ('active','passive')");

                            t.HasCheckConstraint("CK_modifier_definitions_limit_positive_or_null", "\"DefaultLimitPerGame\" IS NULL OR \"DefaultLimitPerGame\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Code = "chirik",
                            ActivationCommand = "!активировать чирик",
                            ActivationCost = 3,
                            Category = "movement_restriction",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 5,
                            Description = "Первые 60 секунд разрешено перемещаться только на корточках.",
                            IconEmoji = "💰",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Чирик",
                            ScoringType = "non_scoring",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "zhazhda",
                            ActivationCommand = "!активировать жажда",
                            ActivationCost = 3,
                            Category = "score",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 2,
                            Description = "Убийства дают нарастающий бонус +5, миссия без убийств даёт штраф 25.",
                            IconEmoji = "💉",
                            IsArchived = false,
                            Kind = "active",
                            MetadataJson = "{\"bonusPerKill\":5,\"missionFailurePenalty\":25}",
                            Name = "Жажда",
                            ScoringType = "conditional_bonus_penalty",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "rashodnik",
                            ActivationCommand = "!активировать расходник",
                            ActivationCost = 4,
                            Category = "loadout",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 4,
                            Description = "Игроки могут заменить один расходник на свой выбор.",
                            IconEmoji = "🎯",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Расходник",
                            ScoringType = "non_scoring",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "trupy",
                            ActivationCommand = "!активировать трупы",
                            ActivationCost = 4,
                            Category = "combat_rule",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Запрет на сжигание трупов.",
                            IconEmoji = "🔥",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Трупы",
                            ScoringType = "non_scoring",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "navyki",
                            ActivationCommand = "!активировать навыки",
                            ActivationCost = 4,
                            Category = "loadout",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 5,
                            Description = "Количество доступных очков навыков уменьшено на 20% (-2 при 10).",
                            IconEmoji = "⚙️",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Навыки",
                            ScoringType = "non_scoring",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "patron",
                            ActivationCommand = "!активировать патрон",
                            ActivationCost = 4,
                            Category = "score",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Если враг убит первой пулей, команда получает +1 убийство в счётчик.",
                            IconEmoji = "🔫",
                            IsArchived = false,
                            Kind = "active",
                            MetadataJson = "{\"bonusKills\":1}",
                            Name = "Патрон",
                            ScoringType = "conditional_bonus",
                            Tier = "low",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "prokaznik",
                            ActivationCommand = "!активировать проказник",
                            ActivationCost = 6,
                            Category = "mentor_intervention",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 2,
                            Description = "Ментор пакостит 5 минут или пока не кончатся обманки.",
                            IconEmoji = "🙊",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Проказник",
                            ScoringType = "non_scoring",
                            Tier = "mid",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "diareya",
                            ActivationCommand = "!активировать диарея",
                            ActivationCost = 7,
                            Category = "behavior_rule",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "При упоминании/обнаружении туалета игрок обязан зайти в него (если нет врага в поле зрения).",
                            IconEmoji = "💩",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Диарея",
                            ScoringType = "non_scoring",
                            Tier = "mid",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "mentorbait",
                            ActivationCommand = "!активировать менторбайт",
                            ActivationCost = 8,
                            Category = "mentor_intervention",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Ментор с шумелками на 5 минут, команда решает как использовать.",
                            IconEmoji = "📣",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Менторбайт",
                            ScoringType = "non_scoring",
                            Tier = "mid",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "kep",
                            ActivationCommand = "!активировать кэп",
                            ActivationCost = 10,
                            Category = "communication_rule",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Только капитан команды может пользоваться голосовым чатом.",
                            IconEmoji = "🔇",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Кэп",
                            ScoringType = "non_scoring",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "feyerverk",
                            ActivationCommand = "!активировать фейерверк",
                            ActivationCost = 11,
                            Category = "mentor_intervention",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Ментор раз в минуту стреляет осветительными снарядами в небо 5 минут.",
                            IconEmoji = "🎆",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Фейерверк",
                            ScoringType = "non_scoring",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "krysa",
                            ActivationCommand = "!активировать крыса",
                            ActivationCost = 12,
                            Category = "mentor_intervention",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Ментор с полным набором ловушек; убийства ментора идут в счёт команды.",
                            IconEmoji = "🐀",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Крыса",
                            ScoringType = "conditional_bonus",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "shot",
                            ActivationCommand = "!активировать шот",
                            ActivationCost = 13,
                            Category = "mentor_intervention",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ментор получает оружие с одним выстрелом, убийство идёт в счёт команды.",
                            IconEmoji = "🥠",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Шот",
                            ScoringType = "conditional_bonus",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "podem",
                            ActivationCommand = "!активировать подъём",
                            ActivationCost = 14,
                            Category = "combat_rule",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Нельзя поднимать союзника, пока не убит враг.",
                            IconEmoji = "☠️",
                            IsArchived = false,
                            Kind = "active",
                            Name = "Подъём",
                            ScoringType = "non_scoring",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "hard75",
                            ActivationCommand = "!активировать хард75",
                            ActivationCost = 18,
                            Category = "score",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLimitPerGame = 1,
                            Description = "Каждое убийство получает множитель +0.75 до восстановления полосок.",
                            IconEmoji = "💀",
                            IsArchived = false,
                            Kind = "active",
                            MetadataJson = "{\"killMultiplierDelta\":0.75}",
                            Name = "Хард75",
                            ScoringType = "multiplier",
                            Tier = "high",
                            UpdatedAtUtc = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.QuestionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AskedTotalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CorrectTotalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAskedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VectorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("VectorCode", "ExternalCode")
                        .IsUnique();

                    b.HasIndex("VectorCode", "Category", "IsEnabled");

                    b.HasIndex("IsDeleted", "IsEnabled", "AskedTotalCount", "LastAskedAtUtc");

                    b.ToTable("question_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_question_definitions_asked_total_non_negative", "\"AskedTotalCount\" >= 0");

                            t.HasCheckConstraint("CK_question_definitions_correct_total_non_negative", "\"CorrectTotalCount\" >= 0");

                            t.HasCheckConstraint("CK_question_definitions_counts_relation", "\"CorrectTotalCount\" <= \"AskedTotalCount\"");

                            t.HasCheckConstraint("CK_question_definitions_reward_non_negative", "\"Reward\" >= 0");

                            t.HasCheckConstraint("CK_question_definitions_soft_delete_semantics", "(\"IsDeleted\" = FALSE AND \"DeletedAtUtc\" IS NULL) OR (\"IsDeleted\" = TRUE AND \"DeletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_question_definitions_sort_order_non_negative", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.QuestionVector", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("question_vectors", null, t =>
                        {
                            t.HasCheckConstraint("CK_question_vectors_code_not_blank", "length(trim(\"Code\")) > 0");
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "viewer",
                            CreatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Viewer role with basic registration capabilities.",
                            Name = "Viewer",
                            UpdatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "moderator",
                            CreatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moderator role that helps manage game operations.",
                            Name = "Moderator",
                            UpdatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "admin",
                            CreatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full management access.",
                            Name = "Administrator",
                            UpdatedAtUtc = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BroadcasterType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TwitchUserType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("backend.Data.Entities.BoardCell", b =>
                {
                    b.HasOne("backend.Data.Entities.GameBoard", "Board")
                        .WithMany("Cells")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("backend.Data.Entities.BoardCellMedia", b =>
                {
                    b.HasOne("backend.Data.Entities.BoardCell", "Cell")
                        .WithMany("MediaLinks")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.MediaAsset", "MediaAsset")
                        .WithMany("CellLinks")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("backend.Data.Entities.GameActiveModifier", b =>
                {
                    b.HasOne("backend.Data.Entities.User", "ActivatedByUser")
                        .WithMany("ActivatedGameModifiers")
                        .HasForeignKey("ActivatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany("ActiveModifiers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.ModifierDefinition", "ModifierDefinition")
                        .WithMany("GameActivations")
                        .HasForeignKey("ModifierCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivatedByUser");

                    b.Navigation("Game");

                    b.Navigation("ModifierDefinition");
                });

            modelBuilder.Entity("backend.Data.Entities.GameBoard", b =>
                {
                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithOne("Board")
                        .HasForeignKey("backend.Data.Entities.GameBoard", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("backend.Data.Entities.GameModifierSelection", b =>
                {
                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany("EnabledModifiers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.ModifierDefinition", "ModifierDefinition")
                        .WithMany("GameSelections")
                        .HasForeignKey("ModifierCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("ModifierDefinition");
                });

            modelBuilder.Entity("backend.Data.Entities.GameParticipationInvitation", b =>
                {
                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.GameParticipationSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("GameId", "SlotId")
                        .HasPrincipalKey("GameId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.GameTeam", "Team")
                        .WithMany()
                        .HasForeignKey("GameId", "TeamId")
                        .HasPrincipalKey("GameId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Slot");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Data.Entities.GameParticipationSlot", b =>
                {
                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany("ParticipationSlots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("backend.Data.Entities.GameQuestionRound", b =>
                {
                    b.HasOne("backend.Data.Entities.User", "AnsweredByUser")
                        .WithMany("AnsweredGameQuestionRounds")
                        .HasForeignKey("AnsweredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Data.Entities.User", "AnsweredForUser")
                        .WithMany("CreditedGameQuestionRounds")
                        .HasForeignKey("AnsweredForUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Data.Entities.User", "AskedByUser")
                        .WithMany("AskedGameQuestionRounds")
                        .HasForeignKey("AskedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.QuestionDefinition", "Question")
                        .WithMany("AskedInGames")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnsweredByUser");

                    b.Navigation("AnsweredForUser");

                    b.Navigation("AskedByUser");

                    b.Navigation("Game");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.Data.Entities.GameTeam", b =>
                {
                    b.HasOne("backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Data.Entities.GameParticipationSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("GameId", "SlotId")
                        .HasPrincipalKey("GameId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("backend.Data.Entities.GameTeamMember", b =>
                {
                    b.HasOne("backend.Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.GameTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("GameId", "TeamId")
                        .HasPrincipalKey("GameId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Entities.ModifierConflict", b =>
                {
                    b.HasOne("backend.Data.Entities.ModifierDefinition", "ConflictsWithModifier")
                        .WithMany()
                        .HasForeignKey("ConflictsWithModifierCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.ModifierDefinition", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConflictsWithModifier");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("backend.Data.Entities.QuestionDefinition", b =>
                {
                    b.HasOne("backend.Data.Entities.QuestionVector", "Vector")
                        .WithMany("Questions")
                        .HasForeignKey("VectorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vector");
                });

            modelBuilder.Entity("backend.Data.Entities.UserRole", b =>
                {
                    b.HasOne("backend.Data.Entities.User", "AssignedByUser")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Data.Entities.BoardCell", b =>
                {
                    b.Navigation("MediaLinks");
                });

            modelBuilder.Entity("backend.Data.Entities.Game", b =>
                {
                    b.Navigation("ActiveModifiers");

                    b.Navigation("Board");

                    b.Navigation("EnabledModifiers");

                    b.Navigation("ParticipationSlots");
                });

            modelBuilder.Entity("backend.Data.Entities.GameBoard", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("backend.Data.Entities.GameTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("backend.Data.Entities.MediaAsset", b =>
                {
                    b.Navigation("CellLinks");
                });

            modelBuilder.Entity("backend.Data.Entities.ModifierDefinition", b =>
                {
                    b.Navigation("GameActivations");

                    b.Navigation("GameSelections");
                });

            modelBuilder.Entity("backend.Data.Entities.QuestionDefinition", b =>
                {
                    b.Navigation("AskedInGames");
                });

            modelBuilder.Entity("backend.Data.Entities.QuestionVector", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("backend.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Data.Entities.User", b =>
                {
                    b.Navigation("ActivatedGameModifiers");

                    b.Navigation("AnsweredGameQuestionRounds");

                    b.Navigation("AskedGameQuestionRounds");

                    b.Navigation("AssignedRoles");

                    b.Navigation("CreditedGameQuestionRounds");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
