export const API_ERROR_CODES = {
  invalidGameSetupTitle: 'game_setup.invalid_title',
  gameSetupStaleVersion: 'game_setup.stale_version',
  gameRegistrationNotOpen: 'game_registration.not_open',
  gameRegistrationNoSlots: 'game_registration.no_slots',
  gameRegistrationAlreadyOnTeam: 'game_registration.already_on_team',
  gameRegistrationTeamNotFound: 'game_registration.team_not_found',
  gameRegistrationTeamNotJoinable: 'game_registration.team_not_joinable',
  gameRegistrationNotTeamMember: 'game_registration.not_team_member',
  gameRegistrationInvitationInvalid: 'game_registration.invitation_invalid',
  gameRegistrationSlotNotFound: 'game_registration.slot_not_found',
  gameRegistrationSlotNotAvailable: 'game_registration.slot_not_available',
  gameRegistrationUserNotFound: 'game_registration.user_not_found',
  gameRegistrationPendingInvitation: 'game_registration.pending_invitation',
  gameRegistrationOperationFailed: 'game_registration.operation_failed',
  gameModifierUnknownCode: 'game_modifier.unknown_code',
  gameModifierGameNotActive: 'game_modifier.game_not_active',
  gameModifierNotEnabled: 'game_modifier.not_enabled',
  gameModifierConflictActive: 'game_modifier.conflict_active',
  gameModifierLimitReached: 'game_modifier.limit_reached',
  gameModifierUserNotResolved: 'game_modifier.user_not_resolved',
} as const
